

namesString="UNDEFINED_KEY,SPACE, RETURN, ESCAPE, TAB, LEFTARROW, RIGHTARROW, UPARROW, DOWNARROW,PAUSE, MINUS, PLUS, TILDE, PERIOD, COMMA, SLASH, LEFTCONTROL,RIGHTCONTROL, LEFTSHIFT, RIGHTSHIFT, F1, F2, F3, F4, F5, F6, F7, F8,F9, F10,F11, F12, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, QR, S, T, U, V, W, X, Y, Z, NUM1, NUM2, NUM3, NUM4, NUM5, NUM6, NUM7,NUM8, NUM9, NUM0, BACKSPACE, EQUAL, BACKSLASH, LEFTALT, RIGHTALT, LEFTBRACKET, RIGHTBRACKET, SEMICOLON, APOSTROPHE, HYPHEN, PAGEUPPAGEDOWN, END, HOME, INSERT, KDELETE, STAR, NUMPAD0, NUMPAD1, NUMPAD2,NUMPAD3, NUMPAD4, NUMPAD5, NUMPAD6, NUMPAD7, NUMPAD8, NUMPAD9,"


names=namesString.split(",")

for i,j in enumerate(names):
    names[i]=j.strip()

finalString=""

for i in names:
    finalString+="\""+i+"\", "
print(finalString)